### ISSUE TITLE
Support for local files

### ISSUE THREAD

**Issue by Rubrene** [mihula/RunEdge#2]
Hello,

after a long search I luckily found your program. It works well, however, I need to open local pdf files,
but when I type
`RunEdge file:///filepath/file.pdf`
in the command line, your wrapper keeps dropping the : of the "file:///" part, so I cannot open the file. As I am too bad in programming to do it myself (only a little bit of Matlab), I would greatly appreciate if you could add this feature.  Thank you :)

**Comment by mihula** [comment]
Hi,
thanks for suggestion, unfortunately it seems to me that Edge team is not supporting opening local files by command call (`microsoft-edge:{url}`) which is used in this super simple exe (source: https://stackoverflow.com/questions/34798285/how-can-i-open-a-local-html-file-in-microsoft-edge-browser).
You may try some other wrappers like edge launcher  - https://github.com/MicrosoftEdge/edge-launcher or similar which is using other approach (at least I suppose that it is more complex than this one).
Rene
